### ISSUE TITLE
config_sample.php comments need corrections

### ISSUE THREAD

**Issue by fritig** [thomas-rcv/admidio-written_communications#22]
config_sample.php 
Zeile 35 Kommentar
$plg_wc_arrCustomFields statt $plg_wc_arrCustomProfileFields
und array ohne => in derselben Zeile

Im weiteren hat die automatische interne Bezeichnung aus "Email 2"die interne Bezeichnung  "E-Mail_2" erstellt. Diese führte zu einem "stummen" Error. Vielleicht wäre ein Hinweis darauf nützlich?

**Comment by Fasse** [comment]
A little bit late, but thanks for the hint.
